### ISSUE TITLE
Unable to easily screenshot certain elements

### ISSUE THREAD

**Issue by beneills** [beneills/cv#3]
## Issue

Github pages tend to have lots of elements which are not uniquely referenceable via CSS (at least with the selectors available in our _Poltergeist_ library).  This means that we're unable to grab the second div in a list, unless they have id's.

XPath selectors would solve this, but we're unable to use them as they don't exist in Poltergeist.  [An issue has been raised about this](https://github.com/teampoltergeist/poltergeist/issues/794).
## Solution
1. Wait for a _Poltergeist/PhantonJS_ fix upstream.
2. Execute Javascript within our _PhantomJS_ session to compute bounding rectangles, and crop full screen images.

**Comment by twalpole** [comment]
What's wrong with nth-child or nth-of-type CSS selectors? They should give you access to the second div in a container

**Comment by beneills** [comment]
@twalpole Great!  That's exactly what I was looking for.  I mis-remembered CSS pseudo classes and was trying `el:nth(n)`.

This solves my use case.
